# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  database: releasehub
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: releasehub_dev

test:
  <<: *default
  database: releasehub_test

production:
  <<: *default
  database: db/production.sqlite3
