# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  database: releasehub
  pool: 5
  username: root
  timeout: 5000
  host: 127.0.0.1

development:
  <<: *default
  database: releasehub_dev

test:
  <<: *default
  database: releasehub_test
